all:
	$(MAKE) -C DAQLogger all;
	$(MAKE) -C Monitor all;
	$(MAKE) -C BestEffortDispatcher all;
	$(MAKE) -C HulScalerReader1 all;
	$(MAKE) -C Drs4QdcReader1 all;
	$(MAKE) -C Drs4QdcReader2 all;
	$(MAKE) -C NIMEASIROCReader1 all;
	$(MAKE) -C NIMEASIROCReader2 all;
clean:
	$(MAKE) -C DAQLogger clean;
	$(MAKE) -C Monitor clean;
	$(MAKE) -C BestEffortDispatcher clean;
	$(MAKE) -C HulScalerReader1 clean;
	$(MAKE) -C Drs4QdcReader1 clean;
	$(MAKE) -C Drs4QdcReader2 clean;
	$(MAKE) -C NIMEASIROCReader1 clean;
	$(MAKE) -C NIMEASIROCReader2 clean;
